### ISSUE TITLE
MAXBUFFER Error

### ISSUE THREAD

**Issue by eouia** [tom-s/clap-detector#11]
Hi.
I've met this error on using your module. 
```
{ RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stderr maxBuffer length exceeded
    at Socket.onChildStderr (child_process.js:374:14)
    at Socket.emit (events.js:187:15)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:260:13)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)
  cmd:
   'sox -t coreaudio default /SOME_PATH/input.wav silence 1 0.0001 5% 1 0.1 5% −−no−show−progress stat' }
```

Used codes are like this;
```js
    this.detector = new ClapDetector(config)

    this.detector.addClapsListener((claps) => {
       console.log(claps)
    }, {number:1, delay:0, force:true})
```
I executed the code and did nothing. Just waiting. After several minutes, that error occurs.

**Comment by tom-s** [comment]
Hi,

I think we need to add a maxBuffer option when calling exec. https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback

**Comment by tom-s** [comment]
I'm not sure it's the correct solution though. Perhaps sox needs to be stopped after a while if nothing happened and be run again to avoid memory issues.

**Comment by eouia** [comment]
I'll try it. Thanks for your efforts.

**Comment by tom-s** [comment]
Feel free to submit a PR if you manage to get it working :-)
