### ISSUE TITLE
Dependency on a vulnerable version of lodash

### ISSUE THREAD

**Issue by laiti** [tom-s/clap-detector#12]
Clap-detector depends on a vulnerable version of lodash (4.17.11.) It should be updated to at least to 4.17.12.

**Comment by laiti** [comment]
PR created: https://github.com/tom-s/clap-detector/pull/13

**Comment by tom-s** [comment]
I'll merge and release a new version soon, thanks for your PR

**Comment by anttilaiti** [comment]
Hi, could you make that release? :)
