### ISSUE TITLE
OSX input source

### ISSUE THREAD

**Issue by beckmx** [tom-s/clap-detector#2]
I was looking the module, very nice, I was wondering if you know which could be the input device config for the built-in mic.

greetings

**Comment by tom-s** [comment]
I should be able to check on a Mac tomorrow. I'm no OS X expert but I know somebody used my module with a Mac. I'll let you know what I find out ! In the meantime you can try passing  coreaudio as conf it might work

**Comment by beckmx** [comment]
yeah that would be helpful, I already tried
var clapConfig = {
   AUDIO_SOURCE: 'Built-in'// default for linux
};
and
var clapConfig = {
   AUDIO_SOURCE: 'coreaudio'// default for linux
};

no luck

**Comment by tom-s** [comment]
Core Audio should work. I'm afraid youll will have to add some debug on your own to find out why it's not working. I'll add some catching and display of errors mechanism in the future to make these things easier

**Comment by luklapp** [comment]
It's working for me on OSX with the following configuration:

`var clapConfig = {
AUDIO_SOURCE: 'coreaudio default'
};`
