### ISSUE TITLE
Microphone for Raspberry Pi 3

### ISSUE THREAD

**Issue by Ricardo1980** [tom-s/clap-detector#3]
Hello!
This project seems interesting.
Can I use it in my Raspberry Pi 3? Do you recommend me any USB microphone? (I don't want to use my GPIO ports, already used).
Thanks a lot.

**Comment by tom-s** [comment]
Hi,

Yeah you can use it on a raspberry Pi 3. Any linux compatible usb microphone should do, personnaly I use this webcam which has incorporated microphone : http://www.logitech.com/fr-be/product/hd-webcam-c270
