### ISSUE TITLE
Sox can't process the arguments given by clap-detector

### ISSUE THREAD

**Issue by snipem** [tom-s/clap-detector#5]
I've logged the cmd that is executed using sox and entered into the command line: 

```
user@server:~/scripts $ sox -t hw:0,0 /home/user/input.wav silence 1 0.0001 10% 1 0.1 10% −−no−show−progress stat
sox:      SoX v14.4.2

sox FAIL sox: Not enough input filenames specified

Usage summary: [gopts] [[fopts] infile]... [fopts] outfile [effect [effopt]]...
...
```
Maybe sox has been changed in the mean time?

Unfortunately this command isn't working. The output of arecord is:

```
user@server:~/scripts $ arecord --list-devices
**** List of CAPTURE Hardware Devices ****
card 0: U0x41e0x30d3 [USB Device 0x41e:0x30d3], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

**Comment by tom-s** [comment]
Hi. Thanks for reporting the issue, I'll have a look in a few days. What OS are you on?

**Comment by snipem** [comment]
The issue appeared first on Linux but is reproducible on OSX. At least for the command set of sox.

**Comment by snipem** [comment]
If found out that the following command is well working on my machine `sox -t alsa default /home/matze/input.wav silence 1 0.0001 10% 1 0.1 10% −−no−show−progress stat`. Maybe you're operating on pulseaudio or something else instead of alsa.

How about logging errors returned from the sox process?

Here is my config anyway:

```
var clapConfig = {
             AUDIO_SOURCE: 'alsa default',
               CLAP_AMPLITUDE_THRESHOLD: 0.1
 };
```

**Comment by tom-s** [comment]
The default config use 'alsa hw:1,0', you may have something different. So if I understand well it fixed your issue ? (if that's the case please feel free to close the issue)

With regard to logging errors, that's a good idea. I don't have time to implement it at the moment but please feel free to make a PR.
