### ISSUE TITLE
Does not handle muptilple claps well

### ISSUE THREAD

**Issue by Shrenos** [tom-s/clap-detector#7]
Clap-detector does detect multiple claps accurately, but it fails to process them properly.
I've set it to turn the screen off on 2 claps and turn it back on on 3 claps.
It doesn't work. The claps overlap, and it only does turn the screen off.
The script calls the shell script as soon as there've been two claps, not waiting for more. That means, if one sets up 2, 3, 4, and 5 clap handlers and claps 5 times, **all of them** will be triggered.
What's more, if I clap 3 times, it's detected as 1 sequence of three claps **and** 2 sequences of 2 claps.

    detected sound
    Clap detected:  [ { id: 1, time: 1546043724202 } ]
    detected sound
    Clap detected:  [ { id: 1, time: 1546043724202 },
      { id: 2, time: 1546043724763 } ]
    2 claps detected. Screen off
    detected sound
    Clap detected:  [ { id: 1, time: 1546043724202 },
      { id: 2, time: 1546043724763 },
      { id: 3, time: 1546043725286 } ]
    3 claps detected. Screen on
    2 claps detected. Screen off

If I remove the 3 claps handler, the 2 claps handler is still triggered twice on three claps:

    Clap detected:  [ { id: 1, time: 1546043865102 } ]
    detected sound
    Clap detected:  [ { id: 1, time: 1546043865102 },
      { id: 2, time: 1546043865662 } ]
    2 claps detected. Screen off
    detected sound
    Clap detected:  [ { id: 1, time: 1546043865102 },
      { id: 2, time: 1546043865662 },
      { id: 3, time: 1546043866276 } ]
    2 claps detected. Screen off

**Comment by tom-s** [comment]
@Shrenos , i've published version 0.5.0 which should work with your scenario. Please be aware that the API changed. Let me know if this works for you !

**Comment by Shrenos** [comment]
Thanks! I'm going to try it.

Meanwhile, I wrote a pretty basic event-driven clap detector-blocker. It works with the previous version.

    clapDetector.onClaps(3, 4000, function (delay) {
        setTimeout((function () {
            for (i = 2; i > 0; i--) {
                console.log('Sendind ' + 'stop_' + i);
                myEmitter.emit('stop_' + i);
            }
        }), 50);
        var action = function () {
            shell.exec('sh /home/shrenos/.scripts/toggle-screen.sh &');
            shell.exec('ls /dev/shm | grep screen-is-');
            console.log('3 claps detected. Screen toggle');
        }
    
    		action();
    
    
    });
    
    clapDetector.onClaps(2, 3000, function (delay) {
        var action = function () {
            console.log('2 claps detected. Electric toggle');
            shell.exec('sh /home/shrenos/.scripts/toggle-right-electric-circuit.sh &');
            shell.exec('ls /dev/shm | grep right-el-is-');
        }
    
        var waitForMore = new Promise(function (resolve, reject) {
            console.log('Waiting for 3 clap confirmation...');
    
            setTimeout((function () {
                resolve('Time Out');
            }), 1000);
            
    
            myEmitter.on('stop_2', () => {
                reject('Oops, more than 2 claps');
            });
    
        })
        waitForMore.then(function (result) {
            action();
            console.log(result); 
        }, function (err) {
            console.log(err); 
        });
    });
